/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';
import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface PageGuitar {}
  interface PageGuitarAttributes extends StencilHTMLAttributes {}

  interface FretBoard {}
  interface FretBoardAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'PageGuitar': Components.PageGuitar;
    'FretBoard': Components.FretBoard;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'page-guitar': Components.PageGuitarAttributes;
    'fret-board': Components.FretBoardAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLPageGuitarElement extends Components.PageGuitar, HTMLStencilElement {}
  var HTMLPageGuitarElement: {
    prototype: HTMLPageGuitarElement;
    new (): HTMLPageGuitarElement;
  };

  interface HTMLFretBoardElement extends Components.FretBoard, HTMLStencilElement {}
  var HTMLFretBoardElement: {
    prototype: HTMLFretBoardElement;
    new (): HTMLFretBoardElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'page-guitar': HTMLPageGuitarElement
    'fret-board': HTMLFretBoardElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'page-guitar': HTMLPageGuitarElement;
    'fret-board': HTMLFretBoardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
